Repository tidyverse/ggplot2, pull requests merged in 2023-09, with the labels that each got.

#5159 Introduction vignette
  vignettes/ggplot2.Rmd
Labels: documentation

#5343 Better scale messages
  NEWS.md
  R/limits.R
  R/scale-.R
  R/scale-alpha.R
  R/scale-binned.R
  R/scale-brewer.R
  R/scale-colour.R
  R/scale-continuous.R
  R/scale-date.R
  R/scale-discrete-.R
  R/scale-gradient.R
  R/scale-grey.R
  R/scale-hue.R
  R/scale-identity.R
  R/scale-linetype.R
  R/scale-linewidth.R
  R/scale-manual.R
  R/scale-shape.R
  R/scale-size.R
  R/scale-steps.R
  R/scale-type.R
  R/scale-viridis.R
  R/zxx.R
  man/binned_scale.Rd
  man/continuous_scale.Rd
  man/datetime_scale.Rd
  man/discrete_scale.Rd
  man/scale_discrete.Rd
  man/scale_gradient.Rd
  man/scale_grey.Rd
  man/scale_hue.Rd
  man/scale_linetype.Rd
  man/scale_manual.Rd
  man/scale_shape.Rd
  man/scale_size.Rd
  man/scale_steps.Rd
  tests/testthat/_snaps/scale-binned.md
  tests/testthat/_snaps/scales.md
  tests/testthat/test-geom-dotplot.R
  tests/testthat/test-scale-colour-continuous.R
  tests/testthat/test-scale-type.R
  tests/testthat/test-scales.R
Labels: scales :snake:, messages

#5304 Only call `zero_range()` and `as.numeric()` in transformed space
  NEWS.md
  R/scale-.R
Labels: feature
